@baseUrl = http://localhost:3000
@bookId = <book_id>
@cursorId = <book_id>
@limit = 3

### DEFAULT LIST WITH 20 BOOKS

GET {{baseUrl}}/books

### SPECIFIC BOOK

GET {{baseUrl}}/books/{{bookId}}

### WITH LIMIT

GET {{baseUrl}}/books?limit={{limit}}

### NEXT PAGE

GET {{baseUrl}}/books?limit=3&cursor={{cursorId}}

### ALL DEMO BOOKS

GET {{baseUrl}}/books?limit=25