GET http://localhost:3000/books
Content-Type: application/json

###

GET http://localhost:3000/books?limit=3
Content-Type: application/json

###
# NEXT PAGE
GET http://localhost:3000/books?limit=3&cursor=ef239041-4566-422d-980e-5cc6ed77557f
Content-Type: application/json

###
# ALL DEMO BOOKS
GET http://localhost:3000/books?limit=25
Content-Type: application/json